services:
  redis:
    container_name: bot_redis
    image: redis:latest
    restart: on-failure
    command: "redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - "7379:6379"
    volumes:
      - "redis-data:/data"
      - "./redis.conf:/usr/local/etc/redis/redis.conf"

  server:
    container_name: bot_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "poetry run python polling.py"
    env_file: ".server.env"
    networks:
      - shared-network
    ports:
      - "8080:8080"
    labels:
      - "logging.promtail=true"
      - "logging_jobname=monopoly_server"
    depends_on:
      - redis

volumes:
  redis-data:

networks:
  shared-network:
    external: true
