"""Single device spy games

Revision ID: d8e19d71bbd1
Revises: a508fe5c545f
Create Date: 2026-05-27 03:07:27.681940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e19d71bbd1'
down_revision: Union[str, Sequence[str], None] = 'a508fe5c545f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('single_device_spy_games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('host_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('secret_word', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('spy_count', sa.String(), nullable=False),
    sa.Column('spy_indices', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_single_device_spy_games_host_id'), 'single_device_spy_games', ['host_id'], unique=False)
    op.create_index(op.f('ix_single_device_spy_games_host_telegram_id'), 'single_device_spy_games', ['host_telegram_id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_single_device_spy_games_host_telegram_id'), table_name='single_device_spy_games')
    op.drop_index(op.f('ix_single_device_spy_games_host_id'), table_name='single_device_spy_games')
    op.drop_table('single_device_spy_games')
    # ### end Alembic commands ###
