"""Impostor games

Revision ID: e377312b44dd
Revises: d8e19d71bbd1
Create Date: 2026-05-28 02:37:09.218491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e377312b44dd'
down_revision: Union[str, Sequence[str], None] = 'd8e19d71bbd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('single_device_impostor_games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('host_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('real_question', sa.String(), nullable=False),
    sa.Column('impostor_question', sa.String(), nullable=False),
    sa.Column('impostor_count', sa.String(), nullable=False),
    sa.Column('impostor_indices', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_single_device_impostor_games_host_id'), 'single_device_impostor_games', ['host_id'], unique=False)
    op.create_index(op.f('ix_single_device_impostor_games_host_telegram_id'), 'single_device_impostor_games', ['host_telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_single_device_impostor_games_host_telegram_id'), table_name='single_device_impostor_games')
    op.drop_index(op.f('ix_single_device_impostor_games_host_id'), table_name='single_device_impostor_games')
    op.drop_table('single_device_impostor_games')
    # ### end Alembic commands ###
